package applications;

import javax.swing.*;
import java.awt.*;

public class ConfigGUI {
    private JPanel mainPanel;
    private JTextPane textPane1;

    public JPanel getMainPanel () {
        return mainPanel;
    }

    public JTextPane getTextPanel () {
        return textPane1;
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$ ();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$ () {
        mainPanel = new JPanel ();
        mainPanel.setLayout (new BorderLayout (0, 0));
        final JScrollPane scrollPane1 = new JScrollPane ();
        mainPanel.add (scrollPane1, BorderLayout.CENTER);
        textPane1 = new JTextPane ();
        scrollPane1.setViewportView (textPane1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$ () {
        return mainPanel;
    }

}
